/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    EntryCard: typeof import('./src/components/entry-card.vue')['default']
    Timer: typeof import('./src/components/timer.vue')['default']
    UiAccordion: typeof import('./src/components/ui/accordion/index.vue')['default']
    UiAccordionContent: typeof import('./src/components/ui/accordion/content.vue')['default']
    UiAccordionItem: typeof import('./src/components/ui/accordion/item.vue')['default']
    UiAccordionTrigger: typeof import('./src/components/ui/accordion/trigger.vue')['default']
    UiBadge: typeof import('./src/components/ui/badge.vue')['default']
    UiButton: typeof import('./src/components/ui/button.vue')['default']
    UiDropdownMenu: typeof import('./src/components/ui/dropdown-menu/index.vue')['default']
    UiDropdownMenuCheckboxItem: typeof import('./src/components/ui/dropdown-menu/checkbox-item.vue')['default']
    UiDropdownMenuContent: typeof import('./src/components/ui/dropdown-menu/content.vue')['default']
    UiDropdownMenuGroup: typeof import('./src/components/ui/dropdown-menu/group.vue')['default']
    UiDropdownMenuItem: typeof import('./src/components/ui/dropdown-menu/item.vue')['default']
    UiDropdownMenuLabel: typeof import('./src/components/ui/dropdown-menu/label.vue')['default']
    UiDropdownMenuPortal: typeof import('./src/components/ui/dropdown-menu/portal.vue')['default']
    UiDropdownMenuRadioGroup: typeof import('./src/components/ui/dropdown-menu/radio-group.vue')['default']
    UiDropdownMenuRadioItem: typeof import('./src/components/ui/dropdown-menu/radio-item.vue')['default']
    UiDropdownMenuSeparator: typeof import('./src/components/ui/dropdown-menu/separator.vue')['default']
    UiDropdownMenuShortcut: typeof import('./src/components/ui/dropdown-menu/shortcut.vue')['default']
    UiDropdownMenuSub: typeof import('./src/components/ui/dropdown-menu/sub.vue')['default']
    UiDropdownMenuSubContent: typeof import('./src/components/ui/dropdown-menu/sub-content.vue')['default']
    UiDropdownMenuSubTrigger: typeof import('./src/components/ui/dropdown-menu/sub-trigger.vue')['default']
    UiDropdownMenuTrigger: typeof import('./src/components/ui/dropdown-menu/trigger.vue')['default']
    UiInput: typeof import('./src/components/ui/input.vue')['default']
  }
}
