CREATE TABLE IF NOT EXISTS entries (
    id INTEGER PRIMARY KEY,
    time_in_seconds INTEGER NOT NULL,
    note TEXT NULL,
    started_at DATETIME NULL,
    type TEXT NOT NULL,
    tracked_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
